#!/usr/bin/env bash
# Fails when a template reads a theme key that has no writer.
#
# The defect this prevents is T011's: the ported templates read ~54 keys through
# ale_get_meta() and ale_get_option(), and the theme registered no metabox, no Customizer
# and no register_post_meta for any of them. Every section was permanently off and nothing
# errored. A test suite seeded by wp-cli would pass against exactly that state.
#
# Method: extract the literal keys the templates read, extract the keys the two schemas
# declare, diff them. Dynamic keys (built by concatenation, e.g. 'servtit' . $i) cannot be
# extracted this way, so they are checked separately by asserting the schema covers the
# numbered variants.

set -uo pipefail

cd "$(dirname "$0")/.."

fail=0
meta_schema=inc/meta.php
option_schema=inc/customizer.php

report() { # side key kind
    echo "  $1  $2 ($3)"
}

echo "consistency: checking theme key coverage"

# --- keys the templates read ----------------------------------------------------
read_meta=$(grep -rhoE "ale_get_meta\(\s*'[a-zA-Z0-9_]+'" --include='*.php' . 2>/dev/null \
    | grep -v node_modules | sed -E "s/.*'([^']+)'/\1/" | sort -u)
read_option=$(grep -rhoE "ale_get_option\(\s*'[a-zA-Z0-9_]+'" --include='*.php' . 2>/dev/null \
    | grep -v node_modules | sed -E "s/.*'([^']+)'/\1/" | sort -u)

# --- keys the schemas declare ---------------------------------------------------
declared_meta=$(grep -oE "^\s+'[a-z0-9_]+'\s*=>\s*\[" "$meta_schema" 2>/dev/null \
    | sed -E "s/^[[:space:]]*'([^']+)'.*/\1/" | sort -u)
declared_option=$(grep -oE "^\s+'[a-z0-9_]+'\s*=>\s*\[" "$option_schema" 2>/dev/null \
    | sed -E "s/^[[:space:]]*'([^']+)'.*/\1/" | sort -u)

# --- dynamic keys ---------------------------------------------------------------
# page-home.php reads ale_get_meta('servic' . $cg_i) etc. Those keys are GENERATED by a
# loop in inc/meta.php rather than written literally, so grepping for 'servtit1' in the
# schema finds nothing and reports a false positive. The honest check is:
#   (a) the base is declared in the generator's field map, and
#   (b) the generator's upper bound matches the template's range.
# (b) matters: if the template loops to 5 and the schema only generates 4, service #5 is
# genuinely unwritable, and only the bounds comparison catches it.
dynamic_bases=$(grep -rhoE "ale_get_meta\(\s*'[a-zA-Z0-9_]+'\s*\." --include='*.php' . 2>/dev/null \
    | sed -E "s/.*'([^']+)'.*/\1/" | sort -u)

# The bound the templates use, from e.g. '$cg_i = 1; $cg_i <= 4'.
#
# Scoped to the files that build DYNAMIC META keys. A repo-wide scan is wrong: this once
# picked up partials/colorselector.php's `for ($cg_scheme = 1; $cg_scheme <= 6; …)`, which
# counts colour schemes and has nothing to do with meta items, and reported a bound of 6
# against a correct schema of 4.
meta_files=$(grep -rlE "ale_get_meta\(\s*'[a-zA-Z0-9_]+'\s*\." --include='*.php' . 2>/dev/null | grep -v node_modules || true)
template_bound=""
if [ -n "$meta_files" ]; then
    # shellcheck disable=SC2086
    template_bound=$(grep -hoE '\$[a-z_]+ *= *1; *\$[a-z_]+ *<= *[0-9]+' $meta_files 2>/dev/null \
        | grep -oE '[0-9]+$' | sort -rn | head -1)
fi
: "${template_bound:=4}"

# The schema's bound. Since the generator moved into cg_meta_repeatable_group() the bound is
# a function default parameter, not a literal in a for-loop — so accept either form. Reading
# only the loop reported 0 here and failed the gate against a correct schema, which is worse
# than having no gate: it teaches people to ignore it.
schema_bound=$(grep -oE '\$count *= *[0-9]+' "$meta_schema" 2>/dev/null \
    | grep -oE '[0-9]+' | sort -rn | head -1)
if [ -z "$schema_bound" ]; then
    schema_bound=$(grep -oE 'for *\(\$[a-z_]+ *= *1; *\$[a-z_]+ *<= *[0-9]+' "$meta_schema" 2>/dev/null \
        | grep -oE '[0-9]+$' | sort -rn | head -1)
fi
: "${schema_bound:=0}"

if [ "$template_bound" != "$schema_bound" ]; then
    echo "  BOUND MISMATCH     template generates 1..${template_bound}, schema generates 1..${schema_bound}"
    fail=1
fi

for base in $dynamic_bases; do
    # The base must be a key in the generator's field map inside inc/meta.php.
    if grep -qE "^\s+'${base}'\s*=>\s*\[" "$meta_schema" 2>/dev/null; then
        continue
    fi
    report "MISSING META KEY" "$base<n>" "read dynamically by a template, not in the generator map"
    fail=1
done

for key in $read_meta; do
    if ! grep -q "^[[:space:]]*'${key}'[[:space:]]*=>" "$meta_schema" 2>/dev/null; then
        # May be a dynamic base rather than a literal schema key.
        if ! grep -q "'${key}'" "$meta_schema" 2>/dev/null; then
            report "MISSING META KEY" "$key" "read by a template, declared in no schema"
            fail=1
        fi
    fi
done

for key in $read_option; do
    if ! grep -q "'${key}'" "$option_schema" 2>/dev/null; then
        report "MISSING OPTION" "$key" "read by a template, absent from $option_schema"
        fail=1
    fi
done

# --- report ---------------------------------------------------------------------
meta_count=$(printf '%s\n' $read_meta | grep -c . || true)
opt_count=$(printf '%s\n' $read_option | grep -c . || true)
dyn_count=$(printf '%s\n' $dynamic_bases | grep -c . || true)
echo "  checked ${meta_count} literal meta keys, ${dyn_count} dynamic bases (x4), ${opt_count} options"

# --- known limitation ------------------------------------------------------------
# This gate extracts LITERAL keys only. A key read through a variable is invisible to it:
# partials/innerheaders.php reads ale_get_option($cg_context['option']) for contactheader,
# galleryheader, eventsheader, menuheader and storyheader, and none of them appear in the
# "checked N options" count. Those five are covered behaviourally instead — tests/e2e/
# partials.spec.ts asserts the header band renders. Do not read the counts below as proof
# that every key in the theme is checked; they are the floor, not the ceiling.

if [ "$fail" -eq 0 ]; then
    echo "consistency: key coverage OK (literal keys only — see the note in this script)"
else
    echo "consistency: FAIL — a template reads a key that nothing can write."
    echo "  Add it to $meta_schema or $option_schema, or stop reading it."
fi
exit $fail
